In [1]:
import numpy as np
import random

In [2]:
global_target = 'Успех фирмы'

In [3]:
targets = ['Максимизация прибыли', 'Максимизация доли рынка']
k = ['Персонал','Капитал','Спрос','Транспорт','Площади']

In [25]:
def mat_gen(mat):
    for i in range(len(mat)):
        for j in range(len(mat)):
            if i>j:
                val = random.randint(1,9)
                mat[i,j],mat[j,i] = val,1/val
    return mat

In [37]:
mat_gen(np.diag((1.,1.)))

array([[1.        , 6.        ],
       [0.16666667, 1.        ]])

In [14]:
round(temp[0,1],4)

0

In [24]:
def mat_g():
    mat = np.diag((1,1))
    val = random.randint(1,9)
    mat[0,1] = val
    mat[1,0] = 1/val
    return mat

In [171]:
k_mats = [mat_g() for _ in range(len(k))]
k_mats

[array([[1, 3],
        [0, 1]]),
 array([[1, 9],
        [0, 1]]),
 array([[1, 1],
        [1, 1]]),
 array([[1, 5],
        [0, 1]]),
 array([[1, 1],
        [1, 1]])]

In [172]:
np.transpose(np.linalg.eig(k_mats)[0])

array([[1., 1., 2., 1., 2.],
       [1., 1., 0., 1., 0.]])

In [173]:
np.diag((1,1,1,1,1))

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])